name: date_converter_app
description: Simple Hijri ↔ Gregorian date converter
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  intl: ^0.20.2
  hijri: ^3.0.0
  path_provider: ^2.1.4
  share_plus: ^11.1.0

  google_mobile_ads: ^6.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icon.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#4E7D5B" # لون خلفية
  adaptive_icon_foreground: "assets/icon.png"
  min_sdk_android: 21 # مهم للـ Android
fonts:
  - family: Tajawal
    fonts:
      - asset: assets/fonts/Tajawal-Regular.ttf
      - asset: assets/fonts/Tajawal-Bold.ttf
        weight: 700
